# Generated by Django 3.2.7 on 2021-09-17 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_chat_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
